name: MacOS

on:
  push:
    branches: [ mobile ]
  pull_request:
    branches: [ mobile ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'
      - uses: actions/checkout@v2
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '21.1.0'
          java: 'java16'
      - name: Make staging directory
        run: mkdir staging
      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}
      - name: Gluon Build
        run: mvn -Pdesktop gluonfx:build gluonfx:package
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
      - name: Show created files
        run: ls -l target/client/x86_64-darwin/
      - name: Copy native client to staging
        run: cp -r target/client/x86_64-darwin/javamagazine* staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

