# https://docs.gluonhq.com/#platforms_android_github_actions
# https://developers.google.com/android/management/service-account
# https://developer.android.com/studio/publish/app-signing
# encode keystore file: openssl base64 -in <infile> -out <outfile>

name: Linux Android

on:
  push:
    branches: [ native ]
  pull_request:
    branches: [ native ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v2
      
      # GraalVM GitHub Actions image
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Create a staging directory where the binary will be copied into
      - name: Make staging directory
        run: mkdir staging

      # Install the Gluon License (optional)
      # Using this step requires you to set a GLUON_LICENSE secret in the secret configuration of your repo. Have a look at https://gluonhq.com/products/mobile/buy for more information about obtaining a license.
      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      # Build your project using Maven
      # The desktop profile is used, which means a native build will be created for the host platform (in this case Linux) itself.
      - name: Gluon Build
        run: mvn -DconsoleProcessLog=true -Pandroid gluonfx:build gluonfx:package
        env:
          ANDROID_KEYSTOREPATH: ${{ steps.android_keystore_file.outputs.filePath }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYALIAS: ${{ secrets.ANDROID_KEYALIAS }}
          ANDROID_KEYALIAS_PASSWORD: ${{ secrets.ANDROID_KEYALIAS_PASSWORD }}

      # List the created files so we know which one to copy in the next step
      - name: Show created files
        run: ls -l target/gluonfx/aarch64-android/gvm/

      - name: Copy native clients to staging
        run: cp -r target/gluonfx/aarch64-android/gvm/javamagazine-fxgl.apk staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      #- name: Upoad to Google Play
      #  uses: r0adkll/upload-google-play@v1
      #  with:
      #    serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #    packageName: be.webtechie.fxgl
      #    releaseFiles: target/client/aarch64-android/gvm/javamagazine-fxgl.apk
      #    track: beta
