# https://docs.gluonhq.com/#platforms_android_github_actions
# https://developers.google.com/android/management/service-account
# https://developer.android.com/studio/publish/app-signing
# encode keystore file: openssl base64 -in <infile> -out <outfile>

name: Linux Android

on:
  push:
    branches: [ mobile ]
  pull_request:
    branches: [ mobile ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '21.1.0'
          java: 'java16'
      - name: APT update
        run: sudo apt update
      - name: Install libraries
        run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
      - name: Make staging directory
        run: mkdir staging
      - name: Setup Android Keystore
        id: android_keystore_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'my.keystore'
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}
      - name: Gluon Build
        run: mvn -DconsoleProcessLog=true -Pandroid client:build client:package
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
          ANDROID_KEYSTOREPATH: ${{ steps.android_keystore_file.outputs.filePath }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYALIAS: ${{ secrets.ANDROID_KEYALIAS }}
          ANDROID_KEYALIAS_PASSWORD: ${{ secrets.ANDROID_KEYALIAS_PASSWORD }}
      - name: Show created files
        run: ls -l target/client/aarch64-android/gvm/
      - name: Copy native clients to staging
        run: cp -r target/client/aarch64-android/gvm/EmojiSnakeGameApp.apk staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
      - name: Upoad to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: be.webtechie.emojisnakegameapp
          releaseFiles: target/client/aarch64-android/gvm/EmojiSnakeGameApp.apk
          track: beta
