name: Linux Native

on:
  push:
    branches: [ native ]
  pull_request:
    branches: [ native ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v2

      # Install extra required packaged on top of ubuntu-latest
      - name: Install libraries
        run: sudo apt update | sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      # GraalVM GitHub Actions image
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Create a staging directory where the binary will be copied into
      - name: Make staging directory
        run: mkdir staging

      # Install the Gluon License (optional)
      # Using this step requires you to set a GLUON_LICENSE secret in the secret configuration of your repo. Have a look at https://gluonhq.com/products/mobile/buy for more information about obtaining a license.
      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      # Build your project using Maven
      # The desktop profile is used, which means a native build will be created for the host platform (in this case Linux) itself.
      - name: Gluon Build
        run: mvn -Pdesktop gluonfx:build gluonfx:package

      # List the created files so we know which one to copy in the next step
      - name: Show created files
        run: ls -l target/gluonfx/x86_64-linux/

      # Copy the native binary to the staging directory
      - name: Copy native image to staging
        run: cp -r target/gluonfx/x86_64-linux/JavaMagazineFXGLDemo staging

      # Upload the staging directory as a build artifact. You will be able to download this after the build finishes
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
